CREATE DATABASE PERSON_INFO350
USE PERSON_INFO350
--1. Find all persons with their department name & code. 
SELECT PERSON.PERSONNAME,DEPARTMENT.DEPARTMENTNAME,DEPARTMENT.DEPARTMENTCODE FROM PERSON 
INNER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
--2. Give department wise maximum & minimum salary with department name.
SELECT MAX(SALARY) AS MAX_SAL,MIN(SALARY) AS MIN_SAL,DEPARTMENT.DEPARTMENTNAME FROM PERSON
INNER JOIN DEPARTMENT 
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME 
--3. Find all departments whose total salary is exceeding 100000.
SELECT SUM(SALARY) AS TOTAL_SAL ,DEPARTMENT.DEPARTMENTNAME FROM PERSON
INNER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING SUM(SALARY)>100000
--4. Retrieve person name, salary & department name who belongs to Jamnagar city.
SELECT PERSON.PERSONNAME,PERSON.SALARY,DEPARTMENT.DEPARTMENTNAME FROM PERSON
LEFT OUTER JOIN DEPARTMENT 
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
WHERE CITY='JAMNAGAR'
--5. Find all persons who does not belongs to any department.
SELECT PERSON.PERSONNAME FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
WHERE DEPARTMENT.DEPARTMENTID IS NULL
--6. Find department wise person counts.
SELECT DEPARTMENT.DEPARTMENTNAME, COUNT(PERSON.PERSONNAME) AS TOTAL_PERSONS FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME 
--7. Find average salary of person who belongs to Ahmedabad city.
SELECT AVG(SALARY) FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
WHERE CITY='AHMEDABAD'
GROUP BY CITY
--8. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly.
(In single column)
SELECT PERSON.PERSONNAME +' EARNS' + ' '+CAST(PERSON.SALARY AS VARCHAR) +' FROM DEPARTMENT '+DEPARTMENT.DEPARTMENTNAME +' MONTHLY'FROM PERSON 
LEFT OUTER JOIN DEPARTMENT 
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
--9. List all departments who have no persons.
SELECT DEPARTMENT.DEPARTMENTNAME FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME 
HAVING COUNT(PERSON.DEPARTMENTID)=0
--10. Find city & department wise total, average & maximum salaries.
SELECT PERSON.CITY,DEPARTMENT.DEPARTMENTNAME,MAX(SALARY) AS MAX_SAL,MIN(SALARY) AS MIN_SAL,SUM(SALARY) AS TOTAL_SAL FROM PERSON
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME,PERSON.CITY
--11. Display Unique city names.
SELECT DISTINCT(PERSON.CITY) FROM PERSON
--12. List out department names in which more than two persons.
SELECT DEPARTMENT.DEPARTMENTNAME FROM PERSON 
LEFT OUTER JOIN DEPARTMENT
ON DEPARTMENT.DEPARTMENTID=PERSON.DEPARTMENTID
GROUP BY DEPARTMENT.DEPARTMENTNAME
HAVING COUNT(PERSON.PERSONNAME)>2
--13. Combine person name’s first three characters with city name’s last three characters in single column.
SELECT LEFT(PERSONNAME,3)+RIGHT(CITY,3) FROM PERSON
--14. Give 10% increment in Computer department employee’s salary.
UPDATE PERSON SET SALARY=(0.1*SALARY)+SALARY
WHERE DEPARTMENTID=(SELECT DEPARTMENTID FROM DEPARTMENT WHERE DEPARTMENTNAME='COMPUTER')
--15. Display all the person name’s who’s joining dates difference with current date is more than 365 days.
SELECT PERSONNAME FROM PERSON WHERE (GETDATE()-JOININGDATE)>365