CREATE PROCEDURE INSERT_DEPARTMENT
@DEPARTMENTID INT,
@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
INSERT INTO DEPARTMENT(DEPARTMENTID,DEPARTMENTNAME)
VALUES(@DEPARTMENTID,@DEPARTMENTNAME)
END
EXEC INSERT_DEPARTMENT 1,'ADMIN'
EXEC INSERT_DEPARTMENT 2,'IT'
EXEC INSERT_DEPARTMENT 3,'HR'
EXEC INSERT_DEPARTMENT 4,'ACCOUNT'
SELECT * FROM DEPARTMENT
------------------------------------------------------------------------------------
CREATE PROCEDURE INSERT_DESIGNATION
@DESIGID INT,
@DESIGNAME VARCHAR(100)
AS
BEGIN
INSERT INTO DESIGNATION(DESIGNATIONID,DESIGNATIONNAME) 
VALUES(@DESIGID,@DESIGNAME)
END
EXEC INSERT_DESIGNATION 11,'JOBBER'
EXEC INSERT_DESIGNATION 12,'WELDER'
EXEC INSERT_DESIGNATION 13,'CLERK'
EXEC INSERT_DESIGNATION 14,'MANAGER'
EXEC INSERT_DESIGNATION 15,'CEO'
SELECT * FROM DESIGNATION
----------------------------------------------------------------------
ALTER PROCEDURE INSERT_PERSON
@FNAME VARCHAR(100),
@LNAME VARCHAR(100),
@SAL DECIMAL(8,2),
@JDATE DATETIME,
@DEPTID INT,
@DESIGID INT
AS
BEGIN 
INSERT INTO PERSON(FIRSTNAME,LASTNAME,SALARY,JOININGDATE,DEPARTMENTID,DESIGNATIONID)
VALUES(@FNAME,@LNAME, @SAL, @JDATE ,@DEPTID ,@DESIGID )
END
EXEC INSERT_PERSON 'RAHUL','ANSHU',56000,'01-01-1990',1,12
EXEC INSERT_PERSON 'HARDIK','HINSU',18000,'1990-09-25',2,11
EXEC INSERT_PERSON 'BHAVIN','KAMANI',25000,'1991-05-14',NULL,11
EXEC INSERT_PERSON 'BHOOMI','PATEL',39000,'2014-02-20',1,13
EXEC INSERT_PERSON 'ROHIT','RAJGOR',17000,'1990-07-23',2,15
EXEC INSERT_PERSON 'PRIYA','MEHTA',25000,'1990-10-18',2,NULL
EXEC INSERT_PERSON 'NEHA','TRIVEDI',18000,'2014-02-20',3,15
SELECT * FROM PERSON
-----------------------------------------------------------------------
CREATE PROCEDURE UPDATE_DEPARTMENT
@DEPARTMENTID INT,
@DEPARTMENTNAME VARCHAR(100)
AS
BEGIN
UPDATE DEPARTMENT SET DEPARTMENTNAME=@DEPARTMENTNAME WHERE DEPARTMENTID=@DEPARTMENTID
END
EXEC UPDATE_DEPARTMENT 1,'ADMIN1'
SELECT * FROM DEPARTMENT
-----------------------------------------------------------------------------
CREATE PROCEDURE UPDATE_DESIGNATION
@DESIGNATIONID INT,
@DESIGNATIONNAME VARCHAR(100)
AS
BEGIN
UPDATE DESIGNATION SET DESIGNATIONNAME=@DESIGNATIONNAME WHERE DESIGNATIONID=@DESIGNATIONID
END
EXEC UPDATE_DESIGNATION 11,'JOB'
SELECT * FROM DESIGNATION
-------------------------------------------------
ALTER PROCEDURE UPDATE_PERSON
@ID INT,
@FNAME VARCHAR(100),
@LNAME VARCHAR(100),
@SAL DECIMAL(8,2),
@JDATE DATETIME,
@DEPTID INT,
@DESIGID INT
AS
BEGIN
UPDATE PERSON SET SALARY=@SAL,FIRSTNAME=@FNAME,LASTNAME=@LNAME,JOININGDATE=@JDATE,DEPARTMENTID=@DEPTID,DESIGNATIONID=@DESIGID
WHERE WORKERID=@ID
END
--------------------------------------------------
CREATE PROCEDURE DELETE_DEPARTMENT
@DEPARTMENTID INT
AS
BEGIN
DELETE FROM DEPARTMENT WHERE DEPARTMENTID=@DEPARTMENTID
END
EXEC DELETE_DEPARTMENT 4
SELECT * FROM DEPARTMENT
----------------------------------------------
CREATE PROCEDURE DELETE_DESIGNATION
@DESIGNATIONID INT
AS
BEGIN
DELETE FROM DESIGNATION WHERE DESIGNATIONID=@DESIGNATIONID
END
EXEC DELETE_DESIGNATION 14
SELECT * FROM DESIGNATION
-------------------------------------------
CREATE PROCEDURE DELETE_PERSON
@WORKERID INT
AS
BEGIN
DELETE FROM PERSON WHERE WORKERID=@WORKERID
END
EXEC DELETE_PERSON 105
SELECT * FROM PERSON
-----------------------------
CREATE PROCEDURE SELECTALL_DEPARTMENT
AS
BEGIN
SELECT * FROM DEPARTMENT
END
EXEC SELECTALL_DEPARTMENT
--------------------------------
CREATE PROCEDURE SELECTALL_DESIGNATION
AS
BEGIN
SELECT * FROM DESIGNATION
END
EXEC SELECTALL_DESIGNATION
-----------------------------
ALTER PROCEDURE SELECTALL_PERSON
AS
BEGIN
SELECT WORKERID,FIRSTNAME,LASTNAME,SALARY,JOININGDATE,DEPARTMENTNAME,DESIGNATIONNAME FROM PERSON 
INNER JOIN DEPARTMENT
ON PERSON.DEPARTMENTID=DEPARTMENT.DEPARTMENTID
INNER JOIN DESIGNATION
ON DESIGNATION.DESIGNATIONID=PERSON.DESIGNATIONID
END
EXEC SELECTALL_PERSON
------------------------------------------














