CREATE DATABASE STOREDPROCEDURE
1.CREATE PROCEDURE PR_MST_CITY_SELECTALL
AS
BEGIN
SELECT * FROM MST_CITY
END
----------------------------------
2.CREATE PROCEDURE  PR_MST_CITY_INSERT
(	@CITYID INT,
	@CITYNAME VARCHAR(250),
	@PINCODE VARCHAR(6),
	@CITYREMARKS VARCHAR(500),
	@STATEID INT
	)
AS
BEGIN
INSERT INTO MST_CITY(
	CITYID,
	CITYNAME,
	PINCODE ,
	CITYREMARKS,
	STATEID)
VALUES(
	@CITYID,
	@CITYNAME,
	@PINCODE,
	@CITYREMARKS,
	@STATEID
)
END
PR_MST_CITY_INSERT 5,'UDAIPUR',360009,GOOD,2
--------------------------------------------------
3.CREATE PROCEDURE PR_MST_CITY_UPDATE 
(	@CITYID INT,
	@CITYNAME VARCHAR(250),
	@PINCODE VARCHAR(6),
	@CITYREMARKS VARCHAR(500),
	@STATEID INT
	)
AS
BEGIN 
UPDATE MST_CITY
SET CITYID=@CITYID,
	CITYNAME=@CITYNAME,
	PINCODE=@PINCODE ,
	CITYREMARKS=@CITYREMARKS,
	STATEID=@STATEID
	
WHERE CITYID=@CITYID
END
PR_MST_CITY_UPDATE 4,'SURAT',365002,'AVG',1
SELECT * FROM MST_CITY
--------------------------------
4.CREATE PROCEDURE PR_MST_CITY_DELETE
@CITYID INT
AS
BEGIN
DELETE FROM MST_CITY WHERE CITYID=@CITYID
END
PR_MST_CITY_DELETE 4
-----------------------------------------
5.CREATE PROCEDURE PR_MST_CITY_SELECTBYPK
@CITYID INT
AS
BEGIN
SELECT * FROM MST_CITY WHERE CITYID=@CITYID
END
PR_MST_CITY_SELECTBYPK 3
----------------------------------------------------------
6.CREATE PROCEDURE PR_MST_CITY_SELECTBYPINCODESTARTWITH360
AS
BEGIN
SELECT * FROM MST_CITY WHERE PINCODE LIKE '360%'
END
------------------------------------------------------------
7.CREATE PROCEDURE PR_MST_CITY_SELECTBYCITYNAMEPINCODE
@CITYNAME VARCHAR(250)
AS
BEGIN
SELECT PINCODE FROM MST_CITY WHERE CITYNAME=@CITYNAME
END
PR_MST_CITY_SELECTBYCITYNAMEPINCODE RAJKOT
---------------------------------------------------------------
8.CREATE PROCEDURE PR_MST_CITY_SELECTBYCITYREMARKS
@CITYREMARKS VARCHAR(500)
AS
BEGIN
SELECT * FROM MST_CITY WHERE CITYREMARKS=@CITYREMARKS
END
PR_MST_CITY_SELECTBYCITYREMARKS GOOD
--------------------------------------------------------
9.CREATE PROCEDURE PR_MST_CITY_SELECTBYSTATEID
@STATEID INT
AS
BEGIN
SELECT * FROM MST_CITY WHERE STATEID=@STATEID
END
PR_MST_CITY_SELECTBYSTATEID 1
-------------------------------------------------
10.CREATE PROCEDURE PR_MST_CITY_SELECTBYSTATEIDCITYID
@STATEID INT
AS
BEGIN
SELECT CITYID FROM MST_CITY WHERE STATEID=@STATEID
END
PR_MST_CITY_SELECTBYSTATEIDCITYID 2
---------------------------------------------------

